In [1]:
import numpy as np

student=np.array([67,78,92,74,65])
student[0]
student[4]

65

In [2]:
import pandas as pd

s1 = pd.Series([67, 78, 92, 74, 65],index=['國文', '英文', '數學', '地理', '歷史'])
s1

國文    67
英文    78
數學    92
地理    74
歷史    65
dtype: int64

In [3]:
s1 + 3

國文    70
英文    81
數學    95
地理    77
歷史    68
dtype: int64

In [4]:
s1['國文'] #使用key-index
s1[0] #使用原生-index

/tmp/ipykernel_51856/3821365550.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0] #使用原生-index

67

In [5]:
for i in s1:
    print(i)

67
78
92
74
65

In [6]:
#numpy的統計,可以套用在pandas
s1

國文    67
英文    78
數學    92
地理    74
歷史    65
dtype: int64

In [7]:
#利用numpy的function做統計
np.sum(s1)

376

In [8]:
np.mean(s1)

75.2

In [9]:
np.std(s1)

9.620810776644555

In [10]:
np.median(s1)

74.0

In [14]:
import pandas as pd
pd.DataFrame({
    "林柔均":[78, 92, 76, 91, 72],
    "YuYu":[72, 81, 92, 94, 69],
    "RouJun":[81, 65, 89, 81, 72],
},index=['國文', '英文', '數學', '地理', '歷史'])

    林柔均  YuYu  RouJun
國文   78    72      81
英文   92    81      65
數學   76    92      89
地理   91    94      81
歷史   72    69      72

In [15]:
import numpy as np
import pandas as pd

data = np.random.randint(60,high=100,size=(50,5))
pd.DataFrame(data,
             index = range(1,51),
             columns=['國文', '英文', '數學', '地理', '歷史']
             )

    國文  英文  數學  地理  歷史
1   89  84  72  79  94
2   91  72  68  82  98
3   97  73  66  97  99
4   95  94  62  90  72
5   81  69  66  61  64
6   79  68  94  76  93
7   82  86  62  74  66
8   66  73  76  88  93
9   68  66  92  94  69
10  92  70  87  89  70
11  74  63  65  79  64
12  63  87  92  94  64
13  82  69  68  71  70
14  61  70  62  66  70
15  79  73  72  60  86
16  80  81  80  71  74
17  84  95  82  71  79
18  95  88  70  93  72
19  73  90  70  78  98
20  88  63  64  99  99
21  85  83  60  88  67
22  69  60  73  85  73
23  84  63  83  63  84
24  91  89  77  80  85
25  91  82  76  69  82
26  92  86  99  75  89
27  69  91  90  76  88
28  91  79  77  67  76
29  77  95  76  64  78
30  94  87  64  65  77
31  63  88  79  95  71
32  86  76  82  98  91
33  66  94  94  73  67
34  71  97  98  96  90
35  63  95  90  82  86
36  99  82  74  64  89
37  91  86  60  65  75
38  95  91  85  60  98
39  96  68  65  92  99
40  91  96  64  81  85
41  66  64  64  98  68
42  66  73  77  89  71
43  63  65  85  64  69
44  79  97  68  63  96
45  91  61  89  62  64
46  93  94  61  75  94
47  85  84  92  92  83
48  96  68  87  90  83
49  91  69  74  85  97
50  87  70  92  83  98