In [1]:
import pandas as pd
df = pd.read_csv('學生成績.csv')
df

    學號   姓名   國文  英文   數學   地理  歷史   總分    平均
0    1  許芳如   94  99   51   61  64  369  73.8
1    2  陳凱翔   51  88   59   84  90  372  74.4
2    3  詹忠光   77  50   65   60  97  349  69.8
3    4  陳樂紫   73  86   96   94  64  413  82.6
4    5  潘英迪   64  64   61   96  95  380  76.0
5    6  李美洋   96  68   68   95  78  405  81.0
6    7  陳怡容   68  71   66   82  99  386  77.2
7    8  錢欣潔   51  51   52   68  60  282  56.4
8    9  林佳光  100  74   98   93  57  422  84.4
9   10   戚亨   51  74   81   85  69  360  72.0
10  11  謝水儒   76  58   88   59  72  353  70.6
11  12  林志喜   87  73   85   62  78  385  77.0
12  13  林清英   91  70   74   77  73  385  77.0
13  14  蔡世馨   75  65   59  100  70  369  73.8
14  15  吳志宣  100  57   81   51  69  358  71.6
15  16  盧冠發   68  77   86   69  95  395  79.0
16  17  郭致恬   67  57   63   61  59  307  61.4
17  18  王梅劭   82  54   76   94  77  383  76.6
18  19  陳建香   50  58   59   70  53  290  58.0
19  20  方筠紹   68  80   56   77  77  358  71.6
20  21  劉佳佩   66  77   85   56  62  346  69.2
21  22  周怡啟   69  85   75   62  93  384  76.8
22  23  張嘉韋   53  54   68   55  73  303  60.6
23  24  黃佩玲  100  76   75   78  72  401  80.2
24  25  翁羽威   52  67  100   99  76  394  78.8
25  26  李雅怡   77  85   89  100  78  429  85.8
26  27  余丞苓   93  74   83   69  71  390  78.0
27  28  錢欣潔   51  77   88   75  92  383  76.6
28  29  彭虹屏   61  99   59   57  69  345  69.0
29  30  郭舜昇   94  73   67   58  76  368  73.6
30  31  劉萬季   55  58   99   84  92  388  77.6
31  32  簡美君   79  65   73   57  58  332  66.4
32  33  吳麗卿   99  72   81   82  62  396  79.2
33  34  王志謙  100  67   55   88  99  409  81.8
34  35  高俊男   58  97   61   64  74  354  70.8
35  36  楊又源   60  96   61   87  54  358  71.6
36  37  周家銘   62  62   98   80  56  358  71.6
37  38  白美珍   90  89   59   62  93  393  78.6
38  39  王志謙   67  51   63   57  90  328  65.6
39  40  王柏聖   57  97   62   98  70  384  76.8
40  41  李立偉   76  91   95   71  58  391  78.2
41  42  柯韋成   92  90   66   90  82  420  84.0
42  43  王士銘   65  59   76   65  85  350  70.0
43  44  張明惟   69  55   50   55  60  289  57.8
44  45  賴昌韻   71  58   91   58  82  360  72.0
45  46  賴昌韻   76  72   97   68  92  405  81.0
46  47  王孝純   97  78   62   88  94  419  83.8
47  48  謝貞妃   90  56   91   59  79  375  75.0
48  49  陳志偉   96  67   64   89  71  387  77.4
49  50  林冠蕙   99  64   78   57  59  357  71.4

In [2]:
df[["姓名", "國文", "英文", "數學"]]

     姓名   國文  英文   數學
0   許芳如   94  99   51
1   陳凱翔   51  88   59
2   詹忠光   77  50   65
3   陳樂紫   73  86   96
4   潘英迪   64  64   61
5   李美洋   96  68   68
6   陳怡容   68  71   66
7   錢欣潔   51  51   52
8   林佳光  100  74   98
9    戚亨   51  74   81
10  謝水儒   76  58   88
11  林志喜   87  73   85
12  林清英   91  70   74
13  蔡世馨   75  65   59
14  吳志宣  100  57   81
15  盧冠發   68  77   86
16  郭致恬   67  57   63
17  王梅劭   82  54   76
18  陳建香   50  58   59
19  方筠紹   68  80   56
20  劉佳佩   66  77   85
21  周怡啟   69  85   75
22  張嘉韋   53  54   68
23  黃佩玲  100  76   75
24  翁羽威   52  67  100
25  李雅怡   77  85   89
26  余丞苓   93  74   83
27  錢欣潔   51  77   88
28  彭虹屏   61  99   59
29  郭舜昇   94  73   67
30  劉萬季   55  58   99
31  簡美君   79  65   73
32  吳麗卿   99  72   81
33  王志謙  100  67   55
34  高俊男   58  97   61
35  楊又源   60  96   61
36  周家銘   62  62   98
37  白美珍   90  89   59
38  王志謙   67  51   63
39  王柏聖   57  97   62
40  李立偉   76  91   95
41  柯韋成   92  90   66
42  王士銘   65  59   76
43  張明惟   69  55   50
44  賴昌韻   71  58   91
45  賴昌韻   76  72   97
46  王孝純   97  78   62
47  謝貞妃   90  56   91
48  陳志偉   96  67   64
49  林冠蕙   99  64   78

In [3]:

#iloc[]
#loc[]
df.iloc[0]

學號       1
姓名     許芳如
國文      94
英文      99
數學      51
地理      61
歷史      64
總分     369
平均    73.8
Name: 0, dtype: object

In [4]:
df.iloc[[0, 3, 5]]

   學號   姓名  國文  英文  數學  地理  歷史   總分    平均
0   1  許芳如  94  99  51  61  64  369  73.8
3   4  陳樂紫  73  86  96  94  64  413  82.6
5   6  李美洋  96  68  68  95  78  405  81.0

In [5]:
df.iloc[0:6]

   學號   姓名  國文  英文  數學  地理  歷史   總分    平均
0   1  許芳如  94  99  51  61  64  369  73.8
1   2  陳凱翔  51  88  59  84  90  372  74.4
2   3  詹忠光  77  50  65  60  97  349  69.8
3   4  陳樂紫  73  86  96  94  64  413  82.6
4   5  潘英迪  64  64  61  96  95  380  76.0
5   6  李美洋  96  68  68  95  78  405  81.0

In [6]:
#同時要欄和列
#iloc[],loc[]
df.iloc[:5,[0,1,3]]

   學號   姓名  英文
0   1  許芳如  99
1   2  陳凱翔  88
2   3  詹忠光  50
3   4  陳樂紫  86
4   5  潘英迪  64

In [7]:
df
df.loc[:5,["學號","姓名","地理"]]

   學號   姓名  地理
0   1  許芳如  61
1   2  陳凱翔  84
2   3  詹忠光  60
3   4  陳樂紫  94
4   5  潘英迪  96
5   6  李美洋  95